//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteWepApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTE()
        {
            this.IMAGES = new HashSet<IMAGE>();
            this.SHARES = new HashSet<SHARE>();
        }
    
        public int Id { get; set; }
        public string NoteTitle { get; set; }
        public string NoteDescription { get; set; }
        public string NoteContent { get; set; }
        public System.DateTime NoteCreatedDate { get; set; }
        public Nullable<System.DateTime> NoteModifiedDate { get; set; }
        public Nullable<int> NoteModifiedId { get; set; }
        public Nullable<int> NoteCategoryId { get; set; }
        public int NoteUserId { get; set; }
        public string NoteSefLink { get; set; }
        public int isActive { get; set; }
        public Nullable<int> privateNoteCategoryId { get; set; }
    
        public virtual CATEGOR CATEGOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGE> IMAGES { get; set; }
        public virtual SYSTEMCATEGOR SYSTEMCATEGOR { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHARE> SHARES { get; set; }
    }
}
