//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteWepApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICATIONSCOMMENT
    {
        public int Id { get; set; }
        public string CommentContent { get; set; }
        public int CommentUserId { get; set; }
        public int CommnetPubId { get; set; }
        public System.DateTime CommentDate { get; set; }
        public int isActive { get; set; }
    
        public virtual PUBLICATION PUBLICATION { get; set; }
        public virtual USER USER { get; set; }
    }
}
