//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteWepApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUBLICATION()
        {
            this.FILES = new HashSet<FILE>();
            this.PUBLICATIONSCOMMENTS = new HashSet<PUBLICATIONSCOMMENT>();
        }
    
        public int Id { get; set; }
        public string PubTitle { get; set; }
        public string PubContent { get; set; }
        public int PubUserId { get; set; }
        public System.DateTime PubCreatedDate { get; set; }
        public Nullable<System.DateTime> PubModifiedDate { get; set; }
        public string PubSefLink { get; set; }
        public int isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILE> FILES { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUBLICATIONSCOMMENT> PUBLICATIONSCOMMENTS { get; set; }
    }
}
