//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteWepApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHARE
    {
        public int Id { get; set; }
        public int ToUserId { get; set; }
        public int FromUserıd { get; set; }
        public int NotId { get; set; }
        public System.DateTime Share_CreatedDate { get; set; }
        public int IsActive { get; set; }
    
        public virtual NOTE NOTE { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
